
SELECT *FROM TAB //테이블 확인



DROP TABLE DEPARTMENT //테이블 없애는 거

purge recyclebin; //남아있는 데이터 삭제


SELECT *FROM EMP

SELECT *FROM DEPARTMENT 

SELECT *FROM COURSE 

SELECT *FROM PROFESSOR 

SELECT *FROM CLASS 

SELECT *FROM TAKES

SELECT *FROM  STUDENT 

UPDATE STUDENT 
SET YEAR =YEAR -1

SELECT  *FROM  PROFESSOR 

UPDATE PROFESSOR 
SET POSITION ='부교수',dept_id='923'
WHERE name='고희석'

DELETE FROM PROFESSOR
WHERE name='김태석'



SELECT *FROM emp;

SELECT *FROM DEPARTMENT 

SELECT *FROM STUDENT s 

SELECT * FROM DEPARTMENT,STUDENT

SELECT name,DEPT_NAME  FROM  DEPARTMENT,STUDENT WHERE department.DEPT_ID =student.DEPT_ID   


SELECT address FROM STUDENT

SELECT DISTINCT address FROM STUDENT

SELECT *FROM PROFESSOR 


SELECT name,2023-YEAR_emp FROM PROFESSOR

SELECT student.NAME ,student.STU_ID ,department.DEPT_NAME 
FROM student,DEPARTMENT
WHERE student.DEPT_ID =department.DEPT_ID


SELECT NAME,"YEAR"  FROM STUDENT  WHERE RESIDENT_ID  LIKE '%*2%' OR RESIDENT_ID LIKE '%*2%'

SELECT name FROM STUDENT

SELECT name FROM PROFESSOR 

SELECT name FROM STUDENT UNION all SELECT NAME FROM PROFESSOR

SELECT * FROM STUDENT 

SELECT student.STU_ID FROM STUDENT,DEPARTMENT WHERE student.DEPT_ID =department.DEPT_ID AND student."YEAR" =3 AND department.DEPT_NAME ='컴퓨터공학과'

SELECT name,stu_id FROM STUDENT WHERE YEAR=3or YEAR=4 ORDER BY name DESC ,STU_ID

SELECT s.name,d.dept_name FROM STUDENT s ,DEPARTMENT d WHERE s.DEPT_ID =d.DEPT_ID 


SELECT ADDRESS  FROM STUDENT WHERE NAME='김광식'

SELECT  name,address FROM STUDENT  WHERE  address ='서울'

SELECT s2.name FROM student s1,STUDENT s2 WHERE s1.ADDRESS =s2.ADDRESS AND s1.NAME ='김광식'

SELECT * FROM STUDENT s1, STUDENT s2 WHERE s1.ADDRESS =s2.ADDRESS AND s1.NAME ='김광식'

SELECT name,POSITION ,2023-year_emp FROM PROFESSOR

SELECT name 이름 ,POSITION  직위 ,2023-YEAR_emp 재직연수 FROM PROFESSOR 

SELECT s.stu_id FROM STUDENT s,DEPARTMENT d ,TAKES t WHERE s.DEPT_ID = d.DEPT_ID 
AND t.STU_ID =s.STU_ID AND dept_name='컴퓨터공학과'AND grade='A+'

SELECT stu_id 
FROM STUDENT s ,DEPARTMENT d
WHERE s.DEPT_ID =d.DEPT_ID AND dept_name='컴퓨터공학과'
INTERSECT 
SELECT STU_ID FROM TAKES WHERE grade='A+'

SELECT stu_id FROM STUDENT s ,DEPARTMENT d 
WHERE s.DEPT_ID =d.DEPT_ID AND DEPT_name='산업공학과'
MINUS 
SELECT STU_ID FROM TAKES
WHERE grade ='A+'

SELECT title,credit,YEAR,semester
FROM COURSE LEFT OUTER JOIN CLASS
USINg(COURSE_id)

SELECT title,credit,YEAR,semester
FROM course,CLASS 
WHERE course.COURSE_ID =class.COURSE_ID(+)


SELECT title,credit,YEAR,semester
FROM COURSE RIGHT OUTER JOIN CLASS
using(COURse_id)

SELECT title,credit,YEAR,semester
FROM COURSE ,CLASS
WHERE course.COURSE_ID(+) =class.COURSE_ID

SELECT title,credit,YEAR,semester
FROM COURSE FULL OUTER JOIN CLASS
USING (course_id)

SELECT *FROM emp

SELECT *
FROM EMP
ORDER BY 6 DESC

SELECT COUNT(*)
FROM STUDENT
WHERE YEAR =3

SELECT *
FROM STUDENT
WHERE YEAR=3


SELECT COUNT(COMM)
FROM EMP

SELECT COUNT(DISTINCT  DEPT_ID) 
FROM STUDENT 

SELECT count(*)
FROM STUDENT s ,DEPARTMENT d
WHERE s.DEPT_ID =d.DEPT_ID AND d.DEPT_NAME ='컴퓨터공학과'

SELECT *
FROM EMP e 

SELECT COUNT(*) 
FROM EMP e 
WHERE e.JOB ='SALESMAN' AND e.SAL>=1500


SELECT sum(2012-YEAR_EMP )
FROM PROFESSOR

SELECT 2012-YEAR_EMP,NAME  
FROM PROFESSOR p 

SELECT SUM(SAL)
FROM EMP e 
WHERE e.JOB ='SALESMAN'


SELECT *
FROM EMP 

SELECT *
FROM DEPT d 

SELECT SUM(sal) 
FROM DEPT d ,EMP e 
WHERE e.DEPTNO =d.DEPTNO  AND DNAME ='RESEARCH'

SELECT AVG(2012-YEAr_emp)
FROM PROFESSOR p

SELECT*
FROM EMP e 


SELECT  AVG(sal) 
FROM EMP e
WHERE e.JOB ='CLERK'

SELECT  AVG(sal) 
FROM EMP e
WHERE e.JOB ='SALESMAN'

SELECT  AVG(sal) 
FROM EMP e
WHERE e.JOB ='MANAGER'

SELECT  AVG(sal) 
FROM EMP e
WHERE e.JOB ='ANALYST'

SELECT  AVG(sal) 
FROM EMP e
WHERE e.JOB ='PRESIDENT'

SELECT  AVG(sal) 
FROM EMP e
WHERE e.JOB ='CLERK'

SELECT MAX(sal) , AVG(SAL),MIN(SAL)  
FROM EMP e ,DEPT d 
WHERE e.DEPTNO =d.DEPTNO AND dname ='ACCOUNTING'

SELECT ename,MAX(sal)
FROM emp
GROUP BY ENAME 

SELECT dept_id,COUNT(*)
FROM STUDENT s 
GROUP BY DEPT_ID 

SELECT dept_name,COUNT(*)
FROM STUDENT s ,DEPARTMENT d
WHERE s.DEPT_ID =d.DEPT_ID 
GROUP BY dept_name

SELECT dname,COUNT(*),AVG(sal),MAX(sal),MIN(sal)
FROM EMP e ,DEPT d
WHERE e.DEPTNO=d.DEPTNO
GROUP BY dname
ORDER BY dname


SELECT dept_name,COUNT(*),AVG(2012-year_emp),MAX(2012-year_emp),MIN(2012-YEAR_EMP) 
FROM PROFESSOR p,DEPARTMENT d 
WHERE p.DEPT_ID =d.DEPT_ID 
GROUP BY DEPT_name

SELECT dept_name ,COUNT(*),AVG(2012-YEAR_emp),max(2012-year_emp)
FROM PROFESSOR p ,DEPARTMENT d
WHERE p.DEPT_ID =d.DEPT_ID 
GROUP BY DEPT_name
--HAVING AVG(2012-year_emp)>=10 

SELECT dname,COUNT(*),AVG(sal),MAX(sal),MIN(sal)
FROM EMP e,DEPT d 
WHERE e.DEPTNO =d.DEPTNO 
GROUP BY dname
HAVING COUNT(*)>=5 

SELECT *
FROM EMP e 
WHERE COMM IS  NOT NULL 

SELECT stu_id
FROM TAKES t
WHERE GRADE <>'A+'

SELECT *
FROM EMP e 
WHERE COMM <>1400

CREATE OR REPLACE VIEW v_takes AS 
SELECT stu_id ,class_id
FROM TAKES t 
